= dotcontrol: a dot file manager

== install

With https://rustup.rs[rustup] and nightly toolchain (`rustup toolchain install nightly`) installed:

* `cargo +nightly install dotcontrol`

This is due to a limitation in Rust and Cargo, that the binary file and crate are the same name.
A solution is https://github.com/rust-lang/cargo/issues/9778[being implemented],
and currently requires nightly.

== a little glossary

- *dot* a tracked file in a profile
- *profile* a set of dots, can be combined

== commands

=== `.c`

Show info about current profile.

=== `.c profile`

Switch to profile `profile`, create first if didn't exist.
Obviously, don't name it after following commands.

=== `.c i profile [profile...]`

Show info about specified profile(s), all if `-a`.

=== `.c ia`

Show info about all profiles.

=== `.c + path [path...] [-p profile[,profile...]] [-a]`

Add or update one or more dots.

If `-p`, add to specified profile(s).

If `-a`, add to all profiles.

=== `.c ++ app [app...]`

Add or update dots following preset `app`(s).

=== `.c - path [path...] [-p profile[,profile...]] [-a]`

Delete one or more dots, i.e. stop tracking.

If `-p`, delete in specified profile(s).

If `-a`, delete in all profiles.

=== `.c -- app [app...]`

Delete dots following preset `app`(s).

=== `.c lp`

List available presets.

=== `.c p- profile [profile...]`

Delete one or more profiles.

=== `.c p= type remote`

Clone remote profile, setting it up as remote.

=== `.c =+ type remote [name]`

Set up sync. Optionally name it, `remote` by default.

=== `.c =- name [name...]`

Shut down specified sync.

=== `.c = [profile [profile...]] [-a]`

Show sync info for current, specified or all (`-a`) profile(s).

=== `.c ==`

Sync currently staged changes. Push to remote if local is newer, and vice versa.

If given arguments, pass to underlying sync program.

=== `.c =]`

Push changes to remote.

If given arguments, pass to underlying sync program.

=== `.c [=`

Pull changes from remote.

If given arguments, pass to underlying sync program.

== license

BSD-3-Clause

(c) 2021 Blair Noctis
